Fix windows build and add github CI
servo/fontsan pull request #26
Opened 2024-01-27 18:38 UTC by jschwe

See the individual commits for details

2024-01-27 18:45 UTC, jschwe commented
@mrobinson I based the github action on your previous MR, but cleaned it up slightly. The github CI passes on my fork: https://github.com/jschwe/fontsan/actions/runs/7680490707

I also fixed some other minor things I stumbled across. Probably it would also be a good idea to update the dependencies to a newer version, but I thought it would be best to get CI running again before attempting to update ots.

2024-01-29 13:53 UTC, mrobinson requested changes
Nicely done. I have a few small suggestions.

2024-01-29 13:53 UTC, mrobinson commented on .github/workflows/test.yml
> +name: fontsan CI
I'm not sure it's necessary to repeat `fontsan` here.

```suggestion
name: CI
```

2024-01-29 13:53 UTC, mrobinson commented on .github/workflows/test.yml
> +on: push
Can you also enable this workflow for pull requests?

2024-01-29 13:53 UTC, mrobinson commented on .github/workflows/test.yml
> +        if: "!success()"
These should be modified to take into account all task dependencies. See https://github.com/servo/webrender/blob/master/.github/workflows/main.yml#L53. This is important for the proper functioning of the merge queue.

2024-01-29 13:53 UTC, mrobinson commented on .github/workflows/test.yml
> +    name: homu build finished
This repository no longer uses homu.

```suggestion
    name: Result
```

2024-01-29 19:13 UTC, jschwe commented
Thanks for the review - I amended the `github CI workflow` commit to include all your suggestions about the workflow

2024-01-31 14:27 UTC, mrobinson commented on .github/workflows/test.yml
> +          RUST_BACKTRACE: 1
```suggestion
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Build
        run: cargo build -vv
      - name: Test
        run: cargo test -vv
        env:
          RUST_BACKTRACE: 1
```

2024-01-31 14:37 UTC, mrobinson approved these changes

2024-01-31 14:41 UTC, merged

2024-01-31 16:58 UTC, mrobinson commented
@jschwe Thanks for your contribution!